on:
  push:

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.17.1" # 改成自己的版本

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o grm_linux_amd64 ./main.go
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o grm_linux_arm64 ./main.go
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o grm_macOs_amd64 ./main.go
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o grm_macOs_arm64 ./main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            tar -czf grm_linux_amd64.tar.gz grm_linux_amd64 conf.yml
            tar -czf grm_linux_arm64.tar.gz grm_linux_arm64 conf.yml
            tar -czf grm_macOs_amd64.tar.gz grm_macOs_amd64 conf.yml
            tar -czf grm_macOs_arm64.tar.gz grm_macOs_arm64 conf.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}